number = int(input('Введите любое трёхзначное число:'))
first_digit = int(number / 100)
second_digit = int((number - first_digit * 100) / 10)
third_digit = int(number % 10)
reversed_number = int(str(third_digit) + str(second_digit) + str(first_digit))
print(reversed_number)
